<?php
require_once __DIR__ . '/../includes/api_auth.php';
require_once __DIR__ . '/../includes/inventory.php';
requireInventoryRead();
$conn=@new mysqli('localhost','root','','pastry_db');
if($conn->connect_error){http_response_code(500);echo json_encode(['success'=>false,'message'=>'Database connection failed']);exit;}
function batchJson(bool $ok,string $message='',array $extra=[],int $status=200):never{http_response_code($status);echo json_encode(array_merge(['success'=>$ok,'message'=>$message],$extra));exit;}
function batchDate($value){if($value===null||trim((string)$value)==='')return null;$value=trim((string)$value);$date=DateTime::createFromFormat('Y-m-d',$value);return $date&&$date->format('Y-m-d')===$value?$value:false;}
if($_SERVER['REQUEST_METHOD']==='GET'){
 $ingredientId=max(0,(int)($_GET['ingredient_id']??0));if(!$ingredientId)batchJson(false,'ingredient_id is required',[],400);$stmt=$conn->prepare("SELECT b.id,b.ingredient_id,b.batch_number,b.quantity_received,b.quantity_remaining,b.purchase_date,b.expiry_date,b.supplier,b.unit_cost,b.notes,b.created_at,u.name AS created_by_name,CASE WHEN b.quantity_remaining<=0 THEN 'Discarded' WHEN EXISTS(SELECT 1 FROM discard_requests d WHERE d.ingredient_batch_id=b.id AND d.status='Pending') THEN 'Pending Approval' WHEN b.expiry_date IS NOT NULL AND b.expiry_date<CURDATE() THEN 'Expired' WHEN i.threshold>0 AND i.stock<=i.threshold THEN 'Low Stock' ELSE 'Good' END AS status FROM ingredient_batches b JOIN ingredients i ON i.id=b.ingredient_id LEFT JOIN users u ON u.id=b.created_by WHERE b.ingredient_id=? ORDER BY b.expiry_date IS NULL,b.expiry_date,b.id DESC");$stmt->bind_param('i',$ingredientId);$stmt->execute();$rows=[];$result=$stmt->get_result();while($row=$result->fetch_assoc()){$row['id']=(int)$row['id'];$row['quantity_received']=(float)$row['quantity_received'];$row['quantity_remaining']=(float)$row['quantity_remaining'];$row['unit_cost']=(float)$row['unit_cost'];$rows[]=$row;}$stmt->close();$conn->close();batchJson(true,'',['batches'=>$rows]);
}
if($_SERVER['REQUEST_METHOD']!=='POST')batchJson(false,'Method not allowed',[],405);$data=json_decode(file_get_contents('php://input'),true);$data=is_array($data)?$data:[];if(($data['action']??'')!=='add_stock')batchJson(false,'Unsupported batch action',[],400);$ingredientId=max(0,(int)($data['ingredient_id']??0));$qty=(float)($data['quantity']??0);$batchNumber=trim((string)($data['batch_number']??''));$purchaseDate=batchDate($data['purchase_date']??null);$expiryDate=batchDate($data['expiry_date']??null);if(!$ingredientId||$qty<=0||$batchNumber==='')batchJson(false,'Ingredient, batch number, and positive quantity are required',[],400);if(!$expiryDate)batchJson(false,'Expiry date is required for stock batches',[],400);if($purchaseDate===false||$expiryDate===false)batchJson(false,'Purchase and expiry dates must use YYYY-MM-DD format',[],400);if($expiryDate&&$purchaseDate&&$expiryDate<$purchaseDate)batchJson(false,'Expiry date cannot be before purchase date',[],400);
$userId=inventoryUserId();$conn->begin_transaction();$lock=$conn->prepare('SELECT name,stock FROM ingredients WHERE id=? FOR UPDATE');$lock->bind_param('i',$ingredientId);$lock->execute();$ingredient=$lock->get_result()->fetch_assoc();$lock->close();if(!$ingredient){$conn->rollback();batchJson(false,'Ingredient not found',[],404);}$exists=$conn->prepare('SELECT id FROM ingredient_batches WHERE ingredient_id=? AND batch_number=? LIMIT 1');$exists->bind_param('is',$ingredientId,$batchNumber);$exists->execute();if($exists->get_result()->num_rows){$exists->close();$conn->rollback();batchJson(false,'This batch number already exists. Please enter a different batch number.',[],409);}$exists->close();$newStock=(float)$ingredient['stock']+$qty;$update=$conn->prepare('UPDATE ingredients SET stock=?,updated_at=NOW() WHERE id=?');$update->bind_param('di',$newStock,$ingredientId);if(!$update->execute()){$update->close();$conn->rollback();batchJson(false,'Unable to update ingredient stock. Please try again.',[],500);}$update->close();$unitCost=(float)($data['unit_cost']??0);$supplier=trim((string)($data['supplier']??''));$notes=trim((string)($data['notes']??''));$insert=$conn->prepare('INSERT INTO ingredient_batches (ingredient_id,batch_number,quantity_received,quantity_remaining,purchase_date,expiry_date,supplier,unit_cost,notes,created_by) VALUES (?,?,?,?,?,?,?,?,?,?)');$insert->bind_param('isddsssdsi',$ingredientId,$batchNumber,$qty,$qty,$purchaseDate,$expiryDate,$supplier,$unitCost,$notes,$userId);if(!$insert->execute()){$insert->close();$conn->rollback();batchJson(false,'Unable to record stock batch. Please try again.',[],500);}$batchId=$insert->insert_id;$insert->close();$note="Stock In batch {$batchNumber}";if(!insertIngredientMovement($conn,$ingredientId,'stock_in',$qty,$note,$userId,'ingredient_batch',$batchId,(float)$ingredient['stock'],$newStock)){$conn->rollback();batchJson(false,'Unable to record stock movement. Please try again.',[],500);}$conn->commit();$conn->close();batchJson(true,'Stock added successfully',['batch_id'=>$batchId,'new_stock'=>$newStock]);
