-- SQL seed: create table and insert ingredients (simple schema)
CREATE TABLE IF NOT EXISTS cake_ingredients (
  id INT AUTO_INCREMENT PRIMARY KEY,
  cake_name VARCHAR(255) NOT NULL,
  component VARCHAR(255),
  ingredient TEXT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Inserts generated from structured ingredient lists
INSERT INTO cake_ingredients (cake_name, component, ingredient) VALUES
('Chocolate Ganache Cake','Chocolate Cake','2 cups all-purpose flour'),
('Chocolate Ganache Cake','Chocolate Cake','2 cups granulated sugar'),
('Chocolate Ganache Cake','Chocolate Cake','3/4 cup unsweetened cocoa powder'),
('Chocolate Ganache Cake','Chocolate Cake','2 teaspoons baking powder'),
('Chocolate Ganache Cake','Chocolate Cake','1 1/2 teaspoons baking soda'),
('Chocolate Ganache Cake','Chocolate Cake','1 teaspoon salt'),
('Chocolate Ganache Cake','Chocolate Cake','2 large eggs'),
('Chocolate Ganache Cake','Chocolate Cake','1 cup milk'),
('Chocolate Ganache Cake','Chocolate Cake','1/2 cup vegetable oil'),
('Chocolate Ganache Cake','Chocolate Cake','2 teaspoons vanilla extract'),
('Chocolate Ganache Cake','Chocolate Cake','1 cup hot coffee or hot water'),
('Chocolate Ganache Cake','Chocolate Ganache','250 grams dark or semi-sweet chocolate, chopped'),
('Chocolate Ganache Cake','Chocolate Ganache','1 cup (240 mL) heavy cream'),
('Chocolate Ganache Cake','Chocolate Ganache','1 tablespoon unsalted butter (optional)'),

('Chocolate S\'mores Cake','Chocolate Cake','2 cups all-purpose flour'),
('Chocolate S\'mores Cake','Chocolate Cake','2 cups granulated sugar'),
('Chocolate S\'mores Cake','Chocolate Cake','3/4 cup unsweetened cocoa powder'),
('Chocolate S\'mores Cake','Chocolate Cake','2 teaspoons baking powder'),
('Chocolate S\'mores Cake','Chocolate Cake','1 1/2 teaspoons baking soda'),
('Chocolate S\'mores Cake','Chocolate Cake','1 teaspoon salt'),
('Chocolate S\'mores Cake','Chocolate Cake','2 large eggs'),
('Chocolate S\'mores Cake','Chocolate Cake','1 cup milk'),
('Chocolate S\'mores Cake','Chocolate Cake','1/2 cup vegetable oil'),
('Chocolate S\'mores Cake','Chocolate Cake','2 teaspoons vanilla extract'),
('Chocolate S\'mores Cake','Chocolate Cake','1 cup hot coffee or hot water'),
('Chocolate S\'mores Cake','Graham Cracker Crust','1 1/2 cups graham cracker crumbs'),
('Chocolate S\'mores Cake','Graham Cracker Crust','1/4 cup granulated sugar'),
('Chocolate S\'mores Cake','Graham Cracker Crust','6 tablespoons unsalted butter, melted'),
('Chocolate S\'mores Cake','Chocolate Ganache Filling','250 grams dark or semi-sweet chocolate, chopped'),
('Chocolate S\'mores Cake','Chocolate Ganache Filling','1 cup (240 mL) heavy cream'),
('Chocolate S\'mores Cake','Chocolate Ganache Filling','1 tablespoon unsalted butter (optional)'),
('Chocolate S\'mores Cake','Marshmallow Frosting','4 large egg whites'),
('Chocolate S\'mores Cake','Marshmallow Frosting','1 cup granulated sugar'),
('Chocolate S\'mores Cake','Marshmallow Frosting','1/4 teaspoon cream of tartar'),
('Chocolate S\'mores Cake','Marshmallow Frosting','1 teaspoon vanilla extract'),

('Chocolate Caramel Cake','Chocolate Cake','2 cups all-purpose flour'),
('Chocolate Caramel Cake','Chocolate Cake','2 cups granulated sugar'),
('Chocolate Caramel Cake','Chocolate Cake','3/4 cup unsweetened cocoa powder'),
('Chocolate Caramel Cake','Chocolate Cake','2 teaspoons baking powder'),
('Chocolate Caramel Cake','Chocolate Cake','1 1/2 teaspoons baking soda'),
('Chocolate Caramel Cake','Chocolate Cake','1 teaspoon salt'),
('Chocolate Caramel Cake','Chocolate Cake','2 large eggs'),
('Chocolate Caramel Cake','Chocolate Cake','1 cup milk'),
('Chocolate Caramel Cake','Chocolate Cake','1/2 cup vegetable oil'),
('Chocolate Caramel Cake','Chocolate Cake','2 teaspoons vanilla extract'),
('Chocolate Caramel Cake','Chocolate Cake','1 cup hot coffee or hot water'),
('Chocolate Caramel Cake','Caramel Filling','1 cup granulated sugar'),
('Chocolate Caramel Cake','Caramel Filling','6 tablespoons unsalted butter'),
('Chocolate Caramel Cake','Caramel Filling','1/2 cup (120 mL) heavy cream'),
('Chocolate Caramel Cake','Caramel Filling','1/2 teaspoon salt (optional, for salted caramel)'),
('Chocolate Caramel Cake','Caramel Filling','1 teaspoon vanilla extract'),
('Chocolate Caramel Cake','Chocolate Ganache','250 grams dark or semi-sweet chocolate, chopped'),
('Chocolate Caramel Cake','Chocolate Ganache','1 cup (240 mL) heavy cream'),
('Chocolate Caramel Cake','Chocolate Ganache','1 tablespoon unsalted butter (optional)'),
('Chocolate Caramel Cake','Toppings','1/4 cup caramel sauce (for drizzling)'),
('Chocolate Caramel Cake','Toppings','50 grams chocolate curls or shaved chocolate (optional)'),
('Chocolate Caramel Cake','Toppings','A pinch flaky sea salt (optional, for salted caramel chocolate cake)'),

('Chocolate Oreo Cake','Chocolate Cake','2 cups all-purpose flour'),
('Chocolate Oreo Cake','Chocolate Cake','2 cups granulated sugar'),
('Chocolate Oreo Cake','Chocolate Cake','3/4 cup unsweetened cocoa powder'),
('Chocolate Oreo Cake','Chocolate Cake','2 teaspoons baking powder'),
('Chocolate Oreo Cake','Chocolate Cake','1 1/2 teaspoons baking soda'),
('Chocolate Oreo Cake','Chocolate Cake','1 teaspoon salt'),
('Chocolate Oreo Cake','Chocolate Cake','2 large eggs'),
('Chocolate Oreo Cake','Chocolate Cake','1 cup milk'),
('Chocolate Oreo Cake','Chocolate Cake','1/2 cup vegetable oil'),
('Chocolate Oreo Cake','Chocolate Cake','2 teaspoons vanilla extract'),
('Chocolate Oreo Cake','Chocolate Cake','1 cup hot coffee or hot water'),
('Chocolate Oreo Cake','Oreo Buttercream Frosting','1 cup (227 g) unsalted butter, softened'),
('Chocolate Oreo Cake','Oreo Buttercream Frosting','4 cups powdered sugar'),
('Chocolate Oreo Cake','Oreo Buttercream Frosting','1/2 cup unsweetened cocoa powder'),
('Chocolate Oreo Cake','Oreo Buttercream Frosting','10–12 Oreo cookies, finely crushed'),
('Chocolate Oreo Cake','Oreo Buttercream Frosting','2 teaspoons vanilla extract'),
('Chocolate Oreo Cake','Oreo Buttercream Frosting','2–4 tablespoons milk or heavy cream'),
('Chocolate Oreo Cake','Chocolate Ganache (Optional)','250 grams dark or semi-sweet chocolate, chopped'),
('Chocolate Oreo Cake','Chocolate Ganache (Optional)','1 cup (240 mL) heavy cream'),
('Chocolate Oreo Cake','Chocolate Ganache (Optional)','1 tablespoon unsalted butter (optional)'),
('Chocolate Oreo Cake','Toppings','8–10 whole Oreo cookies'),
('Chocolate Oreo Cake','Toppings','4–6 Oreo cookies, crushed'),
('Chocolate Oreo Cake','Toppings','50 grams chocolate shavings or curls (optional)'),

('Tiramisu Cake','Vanilla Sponge Cake','2 cups all-purpose flour'),
('Tiramisu Cake','Vanilla Sponge Cake','1 1/2 cups granulated sugar'),
('Tiramisu Cake','Vanilla Sponge Cake','2 teaspoons baking powder'),
('Tiramisu Cake','Vanilla Sponge Cake','1/2 teaspoon salt'),
('Tiramisu Cake','Vanilla Sponge Cake','1/2 cup (113 g) unsalted butter, softened'),
('Tiramisu Cake','Vanilla Sponge Cake','1/2 cup (120 mL) vegetable oil'),
('Tiramisu Cake','Vanilla Sponge Cake','4 large eggs'),
('Tiramisu Cake','Vanilla Sponge Cake','1 cup (240 mL) whole milk'),
('Tiramisu Cake','Vanilla Sponge Cake','2 teaspoons vanilla extract'),
('Tiramisu Cake','Coffee Syrup','1 cup (240 mL) strong brewed coffee or espresso'),
('Tiramisu Cake','Coffee Syrup','2 tablespoons granulated sugar'),
('Tiramisu Cake','Coffee Syrup','1 tablespoon coffee liqueur (optional)'),
('Tiramisu Cake','Mascarpone Cream Frosting','250 grams mascarpone cheese'),
('Tiramisu Cake','Mascarpone Cream Frosting','1 1/2 cups (360 mL) heavy whipping cream'),
('Tiramisu Cake','Mascarpone Cream Frosting','1/2 cup powdered sugar'),
('Tiramisu Cake','Mascarpone Cream Frosting','1 teaspoon vanilla extract'),
('Tiramisu Cake','Toppings','2 tablespoons unsweetened cocoa powder (for dusting)'),
('Tiramisu Cake','Toppings','30 grams dark chocolate, grated or shaved (optional)'),

('Red Velvet Cake','Red Velvet Cake','2 1/2 cups all-purpose flour'),
('Red Velvet Cake','Red Velvet Cake','1 1/2 cups granulated sugar'),
('Red Velvet Cake','Red Velvet Cake','2 tablespoons unsweetened cocoa powder'),
('Red Velvet Cake','Red Velvet Cake','1 teaspoon baking soda'),
('Red Velvet Cake','Red Velvet Cake','1 teaspoon salt'),
('Red Velvet Cake','Red Velvet Cake','2 large eggs'),
('Red Velvet Cake','Red Velvet Cake','1 cup (240 mL) buttermilk'),
('Red Velvet Cake','Red Velvet Cake','1 cup (240 mL) vegetable oil'),
('Red Velvet Cake','Red Velvet Cake','2 teaspoons vanilla extract'),
('Red Velvet Cake','Red Velvet Cake','1 teaspoon white vinegar'),
('Red Velvet Cake','Red Velvet Cake','2 tablespoons red food coloring (liquid) or 1–2 teaspoons red gel food coloring'),
('Red Velvet Cake','Cream Cheese Frosting','227 grams (8 oz) cream cheese, softened'),
('Red Velvet Cake','Cream Cheese Frosting','1/2 cup (113 g) unsalted butter, softened'),
('Red Velvet Cake','Cream Cheese Frosting','4 cups powdered sugar'),
('Red Velvet Cake','Cream Cheese Frosting','1 teaspoon vanilla extract'),
('Red Velvet Cake','Toppings (Optional)','Red velvet cake crumbs'),
('Red Velvet Cake','Toppings (Optional)','White chocolate shavings'),
('Red Velvet Cake','Toppings (Optional)','Fresh berries (such as strawberries or raspberries)'),

('Ube Flan Cake','Ube Cake','2 1/2 cups all-purpose flour'),
('Ube Flan Cake','Ube Cake','1 1/2 cups granulated sugar'),
('Ube Flan Cake','Ube Cake','2 teaspoons baking powder'),
('Ube Flan Cake','Ube Cake','1/2 teaspoon salt'),
('Ube Flan Cake','Ube Cake','3 large eggs'),
('Ube Flan Cake','Ube Cake','1 cup (240 mL) whole milk'),
('Ube Flan Cake','Ube Cake','1/2 cup (120 mL) vegetable oil'),
('Ube Flan Cake','Ube Cake','1 cup (250 g) ube halaya (ube jam)'),
('Ube Flan Cake','Ube Cake','1 teaspoon ube extract'),
('Ube Flan Cake','Ube Cake','1 teaspoon vanilla extract'),
('Ube Flan Cake','Leche Flan','10 large egg yolks'),
('Ube Flan Cake','Leche Flan','1 can (300 mL) sweetened condensed milk'),
('Ube Flan Cake','Leche Flan','1 can (370 mL) evaporated milk'),
('Ube Flan Cake','Leche Flan','1 teaspoon vanilla extract'),
('Ube Flan Cake','Caramel','1 cup granulated sugar'),
('Ube Flan Cake','Caramel','1/4 cup water'),
('Ube Flan Cake','Whipped Cream Frosting (Optional)','2 cups (480 mL) heavy whipping cream'),
('Ube Flan Cake','Whipped Cream Frosting (Optional)','1/4 cup powdered sugar'),
('Ube Flan Cake','Whipped Cream Frosting (Optional)','1 teaspoon vanilla extract'),
('Ube Flan Cake','Toppings (Optional)','Ube halaya (for piping or garnish)'),
('Ube Flan Cake','Toppings (Optional)','Toasted coconut flakes'),
('Ube Flan Cake','Toppings (Optional)','White chocolate shavings'),

('Strawberry Pistachio Cake','Pistachio Cake','2 1/2 cups all-purpose flour'),
('Strawberry Pistachio Cake','Pistachio Cake','1 1/2 cups granulated sugar'),
('Strawberry Pistachio Cake','Pistachio Cake','1 cup finely ground pistachios'),
('Strawberry Pistachio Cake','Pistachio Cake','2 teaspoons baking powder'),
('Strawberry Pistachio Cake','Pistachio Cake','1/2 teaspoon baking soda'),
('Strawberry Pistachio Cake','Pistachio Cake','1/2 teaspoon salt'),
('Strawberry Pistachio Cake','Pistachio Cake','3 large eggs'),
('Strawberry Pistachio Cake','Pistachio Cake','1 cup (240 mL) whole milk'),
('Strawberry Pistachio Cake','Pistachio Cake','1/2 cup (120 mL) vegetable oil'),
('Strawberry Pistachio Cake','Pistachio Cake','1 teaspoon vanilla extract'),
('Strawberry Pistachio Cake','Pistachio Cake','1/2 teaspoon almond extract (optional)'),
('Strawberry Pistachio Cake','Strawberry Filling','2 cups fresh strawberries, diced'),
('Strawberry Pistachio Cake','Strawberry Filling','1/4 cup granulated sugar'),
('Strawberry Pistachio Cake','Strawberry Filling','1 tablespoon cornstarch'),
('Strawberry Pistachio Cake','Strawberry Filling','1 tablespoon lemon juice'),
('Strawberry Pistachio Cake','Cream Cheese Frosting','227 grams (8 oz) cream cheese, softened'),
('Strawberry Pistachio Cake','Cream Cheese Frosting','1/2 cup (113 g) unsalted butter, softened'),
('Strawberry Pistachio Cake','Cream Cheese Frosting','4 cups powdered sugar'),
('Strawberry Pistachio Cake','Cream Cheese Frosting','1 teaspoon vanilla extract'),
('Strawberry Pistachio Cake','Toppings','1 cup fresh strawberries, halved or sliced'),
('Strawberry Pistachio Cake','Toppings','1/2 cup chopped pistachios'),
('Strawberry Pistachio Cake','Toppings','White chocolate shavings (optional)'),

('Carrot Cake','Carrot Cake','2 cups all-purpose flour'),
('Carrot Cake','Carrot Cake','1 1/2 cups granulated sugar'),
('Carrot Cake','Carrot Cake','1 cup brown sugar'),
('Carrot Cake','Carrot Cake','2 teaspoons baking powder'),
('Carrot Cake','Carrot Cake','1 teaspoon baking soda'),
('Carrot Cake','Carrot Cake','1 teaspoon ground cinnamon'),
('Carrot Cake','Carrot Cake','1/2 teaspoon ground nutmeg'),
('Carrot Cake','Carrot Cake','1/2 teaspoon salt'),
('Carrot Cake','Carrot Cake','4 large eggs'),
('Carrot Cake','Carrot Cake','1 cup (240 mL) vegetable oil'),
('Carrot Cake','Carrot Cake','3 cups finely grated carrots'),
('Carrot Cake','Carrot Cake','1 teaspoon vanilla extract'),
('Carrot Cake','Carrot Cake','1/2 cup chopped walnuts or pecans (optional)'),
('Carrot Cake','Carrot Cake','1/2 cup raisins (optional)'),
('Carrot Cake','Cream Cheese Frosting','227 grams (8 oz) cream cheese, softened'),
('Carrot Cake','Cream Cheese Frosting','1/2 cup (113 g) unsalted butter, softened'),
('Carrot Cake','Cream Cheese Frosting','4 cups powdered sugar'),
('Carrot Cake','Cream Cheese Frosting','1 teaspoon vanilla extract'),
('Carrot Cake','Toppings (Optional)','1/4 cup chopped walnuts or pecans'),
('Carrot Cake','Toppings (Optional)','Carrot cake crumbs'),
('Carrot Cake','Toppings (Optional)','Shredded carrots for garnish'),

('Sans Rival','Cashew Meringue Layers','10 large egg whites'),
('Sans Rival','Cashew Meringue Layers','1 cup granulated sugar'),
('Sans Rival','Cashew Meringue Layers','1 cup powdered sugar'),
('Sans Rival','Cashew Meringue Layers','2 cups (250 g) roasted cashew nuts, finely chopped'),
('Sans Rival','Cashew Meringue Layers','1/4 teaspoon cream of tartar'),
('Sans Rival','French Buttercream','10 large egg yolks'),
('Sans Rival','French Buttercream','1 cup granulated sugar'),
('Sans Rival','French Buttercream','1 cup (240 mL) water'),
('Sans Rival','French Buttercream','2 cups (454 g) unsalted butter, softened'),
('Sans Rival','French Buttercream','1 teaspoon vanilla extract'),
('Sans Rival','Toppings','1 cup (125 g) roasted cashew nuts, coarsely chopped'),
('Sans Rival','Toppings','2 tablespoons powdered sugar (optional, for dusting)'),

('Chocolate Mousse Cake','Chocolate Cake Base','1 1/2 cups all-purpose flour'),
('Chocolate Mousse Cake','Chocolate Cake Base','1 1/2 cups granulated sugar'),
('Chocolate Mousse Cake','Chocolate Cake Base','1/2 cup unsweetened cocoa powder'),
('Chocolate Mousse Cake','Chocolate Cake Base','1 1/2 teaspoons baking powder'),
('Chocolate Mousse Cake','Chocolate Cake Base','1 teaspoon baking soda'),
('Chocolate Mousse Cake','Chocolate Cake Base','1/2 teaspoon salt'),
('Chocolate Mousse Cake','Chocolate Cake Base','2 large eggs'),
('Chocolate Mousse Cake','Chocolate Cake Base','3/4 cup (180 mL) milk'),
('Chocolate Mousse Cake','Chocolate Cake Base','1/3 cup (80 mL) vegetable oil'),
('Chocolate Mousse Cake','Chocolate Cake Base','1 teaspoon vanilla extract'),
('Chocolate Mousse Cake','Chocolate Cake Base','3/4 cup (180 mL) hot coffee or hot water'),
('Chocolate Mousse Cake','Chocolate Mousse','250 grams dark or semi-sweet chocolate, chopped'),
('Chocolate Mousse Cake','Chocolate Mousse','2 cups (480 mL) heavy whipping cream, divided'),
('Chocolate Mousse Cake','Chocolate Mousse','2 tablespoons granulated sugar'),
('Chocolate Mousse Cake','Chocolate Mousse','1 teaspoon vanilla extract'),
('Chocolate Mousse Cake','Chocolate Mousse','1 teaspoon unflavored gelatin (optional, for a firmer mousse)'),
('Chocolate Mousse Cake','Chocolate Mousse','2 tablespoons water (if using gelatin)'),
('Chocolate Mousse Cake','Chocolate Ganache','200 grams dark or semi-sweet chocolate, chopped'),
('Chocolate Mousse Cake','Chocolate Ganache','3/4 cup (180 mL) heavy cream'),
('Chocolate Mousse Cake','Toppings (Optional)','Chocolate curls or shavings'),
('Chocolate Mousse Cake','Toppings (Optional)','Unsweetened cocoa powder'),
('Chocolate Mousse Cake','Toppings (Optional)','Fresh berries'),
('Chocolate Mousse Cake','Toppings (Optional)','Whipped cream'),

('Blueberry Cheesecake','Graham Cracker Crust','2 cups graham cracker crumbs'),
('Blueberry Cheesecake','Graham Cracker Crust','1/4 cup granulated sugar'),
('Blueberry Cheesecake','Graham Cracker Crust','1/2 cup (113 g) unsalted butter, melted'),
('Blueberry Cheesecake','Cheesecake Filling','680 grams (24 oz) cream cheese, softened'),
('Blueberry Cheesecake','Cheesecake Filling','1 cup (240 mL) granulated sugar'),
('Blueberry Cheesecake','Cheesecake Filling','3 large eggs'),
('Blueberry Cheesecake','Cheesecake Filling','1 cup (240 mL) sour cream'),
('Blueberry Cheesecake','Cheesecake Filling','1 teaspoon vanilla extract'),
('Blueberry Cheesecake','Cheesecake Filling','1 tablespoon all-purpose flour (optional, for added stability)'),
('Blueberry Cheesecake','Blueberry Topping','2 cups fresh or frozen blueberries'),
('Blueberry Cheesecake','Blueberry Topping','1/4 cup granulated sugar'),
('Blueberry Cheesecake','Blueberry Topping','1 tablespoon cornstarch'),
('Blueberry Cheesecake','Blueberry Topping','2 tablespoons water'),
('Blueberry Cheesecake','Blueberry Topping','1 tablespoon lemon juice'),
('Blueberry Cheesecake','Toppings (Optional)','Fresh blueberries'),
('Blueberry Cheesecake','Toppings (Optional)','Whipped cream'),
('Blueberry Cheesecake','Toppings (Optional)','Lemon zest'),

('Choco-Pistachio Dream Cake','Chocolate Cake','2 cups all-purpose flour'),
('Choco-Pistachio Dream Cake','Chocolate Cake','2 cups granulated sugar'),
('Choco-Pistachio Dream Cake','Chocolate Cake','3/4 cup unsweetened cocoa powder'),
('Choco-Pistachio Dream Cake','Chocolate Cake','2 teaspoons baking powder'),
('Choco-Pistachio Dream Cake','Chocolate Cake','1 1/2 teaspoons baking soda'),
('Choco-Pistachio Dream Cake','Chocolate Cake','1 teaspoon salt'),
('Choco-Pistachio Dream Cake','Chocolate Cake','2 large eggs'),
('Choco-Pistachio Dream Cake','Chocolate Cake','1 cup (240 mL) milk'),
('Choco-Pistachio Dream Cake','Chocolate Cake','1/2 cup (120 mL) vegetable oil'),
('Choco-Pistachio Dream Cake','Chocolate Cake','2 teaspoons vanilla extract'),
('Choco-Pistachio Dream Cake','Chocolate Cake','1 cup (240 mL) hot coffee or hot water'),
('Choco-Pistachio Dream Cake','Pistachio Cream Filling','1 cup (250 g) pistachio spread or pistachio cream'),
('Choco-Pistachio Dream Cake','Pistachio Cream Filling','1 cup (240 mL) heavy whipping cream'),
('Choco-Pistachio Dream Cake','Pistachio Cream Filling','227 grams (8 oz) cream cheese, softened'),
('Choco-Pistachio Dream Cake','Pistachio Cream Filling','1/4 cup powdered sugar'),
('Choco-Pistachio Dream Cake','Chocolate Ganache','250 grams dark or semi-sweet chocolate, chopped'),
('Choco-Pistachio Dream Cake','Chocolate Ganache','1 cup (240 mL) heavy cream'),
('Choco-Pistachio Dream Cake','Chocolate Ganache','1 tablespoon unsalted butter (optional)'),
('Choco-Pistachio Dream Cake','Toppings','1/2 cup chopped roasted pistachios'),
('Choco-Pistachio Dream Cake','Toppings','50 grams dark chocolate shavings or curls'),
('Choco-Pistachio Dream Cake','Toppings','Chocolate drizzle (optional)');

-- End of seed
